package no.nav.dokarkivavlevering.avsluttAlleSakerPaaTema;

public enum Arbeidsstatus {
	HENTET_FRA_PDL,
	SKAL_IKKE_HENTE_FRA_PDL,
	PDL_FANT_IKKE_NY_AKTOERID,
	SAK_AVSLUTTET,
	PROSESSERING_AV_ARKIVSAK_STARTET,
	FEIL_AAPEN_JOURNALPOST,
	FEIL_ADMINISTRATIV_ENHET_MANGLER,
	FERDIG_TOM_ARKIVSAK
}