package no.nav.dokarkivavlevering.avsluttAlleSakerPaaTema;

public enum Arbeidsstatus {
	HENTET_FRA_PDL,
	SKAL_IKKE_HENTE_FRA_PDL,
	PDL_FANT_IKKE_NY_AKTOERID,
	SAK_AVSLUTTET,
	PROSESSERING_AV_ARKIVSAK_STARTET,
	FEIL_AAPEN_JOURNALPOST,
	FEIL_INGEN_JPER_I_GYLDIG_STATUS_MED_JFR_ENHET,
	FEIL_INGEN_ADMINISTRATIV_ENHET,
	FERDIG_TOM_ARKIVSAK
}