<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<artifactId>dokarkivavlevering</artifactId>
		<groupId>no.nav.dokarkivavlevering</groupId>
		<version>1.0-SNAPSHOT</version>
	</parent>

	<artifactId>arkivverket-schemas</artifactId>
	<packaging>jar</packaging>

	<dependencies>
		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.jvnet.jaxb2.maven2</groupId>
				<artifactId>maven-jaxb2-plugin</artifactId>
				<version>0.14.0</version>
				<executions>
					<execution>
						<id>generate-jaxb-noark5-arkivstruktur</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<generatePackage>no.arkivverket.standarder.noark5.arkivstruktur</generatePackage>
							<schemaDirectory>${project.basedir}/src/main/resources/</schemaDirectory>
							<schemaIncludes>
								<include>arkivstruktur.xsd</include>
							</schemaIncludes>
							<bindingDirectory>${project.basedir}/src/main/resources/</bindingDirectory>
							<bindingIncludes>
								<include>arkivstruktur.xjb</include>
							</bindingIncludes>
							<generateDirectory>${project.build.directory}/generated-sources/arkivstruktur
							</generateDirectory>
							<strict>false</strict>
							<plugins>
								<plugin>
									<groupId>org.jvnet.jaxb2_commons</groupId>
									<artifactId>jaxb2-basics</artifactId>
									<version>${jaxb2-commons.version}</version>
								</plugin>
								<plugin>
									<groupId>org.jvnet.jaxb2_commons</groupId>
									<artifactId>jaxb2-basics-annotate</artifactId>
									<version>${jaxb2-commons.version}</version>
								</plugin>
							</plugins>
							<args>
								<arg>-Xannotate</arg>
							</args>
						</configuration>
					</execution>
					<execution>
						<id>generate-jaxb-noark5-endringslogg</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<generatePackage>no.arkivverket.standarder.noark5.endringslogg</generatePackage>
							<schemaDirectory>${project.basedir}/src/main/resources/</schemaDirectory>
							<schemaIncludes>
								<include>endringslogg.xsd</include>
							</schemaIncludes>
							<bindingDirectory>${project.basedir}/src/main/resources/</bindingDirectory>
							<generateDirectory>${project.build.directory}/generated-sources/endringslogg
							</generateDirectory>
							<strict>false</strict>
							<plugins>
								<plugin>
									<groupId>org.jvnet.jaxb2_commons</groupId>
									<artifactId>jaxb2-basics</artifactId>
									<version>${jaxb2-commons.version}</version>
								</plugin>
								<plugin>
									<groupId>org.jvnet.jaxb2_commons</groupId>
									<artifactId>jaxb2-basics-annotate</artifactId>
									<version>${jaxb2-commons.version}</version>
								</plugin>
							</plugins>
							<args>
								<arg>-Xannotate</arg>
							</args>
						</configuration>
					</execution>
					<execution>
						<id>generate-jaxb-noark5-loependejournal</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<generatePackage>no.arkivverket.standarder.noark5.loependejournal</generatePackage>
							<schemaDirectory>${project.basedir}/src/main/resources/</schemaDirectory>
							<schemaIncludes>
								<include>loependeJournal.xsd</include>
							</schemaIncludes>
							<bindingDirectory>${project.basedir}/src/main/resources/</bindingDirectory>
							<generateDirectory>${project.build.directory}/generated-sources/loependejournal
							</generateDirectory>
							<strict>false</strict>
							<plugins>
								<plugin>
									<groupId>org.jvnet.jaxb2_commons</groupId>
									<artifactId>jaxb2-basics</artifactId>
									<version>${jaxb2-commons.version}</version>
								</plugin>
								<plugin>
									<groupId>org.jvnet.jaxb2_commons</groupId>
									<artifactId>jaxb2-basics-annotate</artifactId>
									<version>${jaxb2-commons.version}</version>
								</plugin>
							</plugins>
							<args>
								<arg>-Xannotate</arg>
							</args>
						</configuration>
					</execution>
					<execution>
						<id>generate-jaxb-noark5-offentligjournal</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<generatePackage>no.arkivverket.standarder.noark5.offentligjournal</generatePackage>
							<schemaDirectory>${project.basedir}/src/main/resources/</schemaDirectory>
							<schemaIncludes>
								<include>offentligJournal.xsd</include>
							</schemaIncludes>
							<bindingDirectory>${project.basedir}/src/main/resources/</bindingDirectory>
							<generateDirectory>${project.build.directory}/generated-sources/offentligjournal
							</generateDirectory>
							<strict>false</strict>
							<plugins>
								<plugin>
									<groupId>org.jvnet.jaxb2_commons</groupId>
									<artifactId>jaxb2-basics</artifactId>
									<version>${jaxb2-commons.version}</version>
								</plugin>
								<plugin>
									<groupId>org.jvnet.jaxb2_commons</groupId>
									<artifactId>jaxb2-basics-annotate</artifactId>
									<version>${jaxb2-commons.version}</version>
								</plugin>
							</plugins>
							<args>
								<arg>-Xannotate</arg>
							</args>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
