server.shutdown=graceful
spring.main.banner-mode=off

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.schema=JOARK

sftp.port=22
sftp.remoteFilePath=inbound
camel.springboot.main-run-controller = true