logging.config=classpath:logback-spring.xml
spring.main.banner-mode=off
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.schema=JOARK

#camel
camel.springboot.main-run-controller = true