apiVersion: batch/v1
kind: Job
metadata:
  name: dokarkivavlevering
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 1
  template:
    spec:
      imagePullSecrets:
        - name: gpr-credentials
      serviceAccountName: default
      restartPolicy: Never
      containers:
        - name: dokarkivavlevering
          image: {{image}}
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "6144Mi"
              cpu: "4000m"
          volumeMounts:
            - mountPath: /var/run/secrets/nais.io/vault
              name: vault-secrets
              subPath: subpath/var/run/secrets/nais.io/vault
            - mountPath: /var/run/secrets/nais.io/service_user
              name: vault-secrets
              subPath: subpath/var/run/secrets/nais.io/service_user
            - mountPath: /var/run/secrets/nais.io/service_user_linux
              name: vault-secrets
              subPath: subpath/var/run/secrets/nais.io/service_user_linux
            - mountPath: /var/run/secrets/nais.io/database_user
              name: vault-secrets
              subPath: subpath/var/run/secrets/nais.io/database_user
          env:
            - name: SPRING_LDAP_URLS
              value: "{{SPRING_LDAP_URLS}}"
            - name: SPRING_DATASOURCE_URL
              value: "{{SPRING_DATASOURCE_URL}}"
            - name: VAULT_TOKEN_PATH
              value: /var/run/secrets/nais.io/vault/vault_token
            - name: AVLEVERING_PDLURL
              value: "{{PDL_URL}}"
            - name: AVLEVERING_EREGURL
              value: "{{EREG_URL}}"
            - name: AVLEVERING_STSTOKENURL
              value: "{{SECURITY_TOKEN_SERVICE_TOKEN_URL}}"
            - name: AVLEVERING_ACTIVEDIRECTORY_BASEDN
              value: "{{AD_NAVUSER_BASEDN}}"
            - name: AVLEVERING_PERIODE_STARTDATO
              value: "{{periodestart}}"
            - name: AVLEVERING_PERIODE_SLUTTDATO
              value: "{{periodeslutt}}"
      initContainers:
        - name: vks-init
          image: navikt/vault-sidekick:v0.3.10-d122b16
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          volumeMounts:
            - mountPath: /var/run/secrets/nais.io/vault
              name: vault-secrets
              subPath: subpath/var/run/secrets/nais.io/vault
            - mountPath: /var/run/secrets/nais.io/service_user
              name: vault-secrets
              subPath: subpath/var/run/secrets/nais.io/service_user
            - mountPath: /var/run/secrets/nais.io/service_user_linux
              name: vault-secrets
              subPath: subpath/var/run/secrets/nais.io/service_user_linux
            - mountPath: /var/run/secrets/nais.io/database_user
              name: vault-secrets
              subPath: subpath/var/run/secrets/nais.io/database_user
          args:
            - -v=10
            - -logtostderr
            - -vault=https://vault.adeo.no
            - -one-shot
            - -save-token=/var/run/secrets/nais.io/vault/vault_token
            - -cn=secret:{{VAULT_KV_PATH}}:dir=/var/run/secrets/nais.io/vault,fmt=flatten,retries=1
            - -cn=secret:{{SRVDOKAVLEVERING}}:dir=/var/run/secrets/nais.io/service_user,fmt=flatten,retries=1
            - -cn=secret:{{SRV_LINUX}}:dir=/var/run/secrets/nais.io/service_user_linux,fmt=flatten,retries=1
            - -cn=secret:{{VAULT_DATABASE_CREDS}}:dir=/var/run/secrets/nais.io/database_user,fmt=flatten,retries=1
          env:
            - name: VAULT_AUTH_METHOD
              value: kubernetes
            - name: VAULT_SIDEKICK_ROLE
              value: dokarkivavlevering
            - name: VAULT_K8S_LOGIN_PATH
              value: {{VAULT_K8S_LOGIN_PATH}}
      volumes:
        - name: vault-secrets
          emptyDir:
            medium: Memory
