apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: dokarkivavlevering
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  ttlSecondsAfterFinished: 100
  image: {{image}}
  resources:
    requests:
      memory: "1024Mi"
      cpu: "100m"
    limits:
      memory: "8192Mi"
      cpu: "4000m"
  filesFrom:
    - secret: dokarkivavlevering
      mountPath: /var/run/secrets/nais_secrets
  envFrom:
    - secret: dokarkivavlevering
  env:
    - name: JAVA_TRUSTSTORE_OPTIONS
      value: "-Djavax.net.ssl.trustStore=$(NAV_TRUSTSTORE_PATH)
              -Djavax.net.ssl.trustStorePassword=$(NAV_TRUSTSTORE_PASSWORD)"
    - name: JDK_JAVA_OPTIONS
      value: "-XX:MaxRAMPercentage=75
              $(JAVA_PROXY_OPTIONS) $(JAVA_TRUSTSTORE_OPTIONS)"
    - name: SPRING_LDAP_URLS
      value: "{{SPRING_LDAP_URLS}}"
    - name: DOKARKIVAVLEVERING_ENDPOINTS_DATAVAREHUS_URL
      value: "{{DOKARKIVAVLEVERING_ENDPOINTS_DATAVAREHUS_URL}}"
    - name: DOKARKIVAVLEVERING_ENDPOINTS_EREG_URL
      value: "{{DOKARKIVAVLEVERING_ENDPOINTS_EREG_URL}}"
    - name: DOKARKIVAVLEVERING_ENDPOINTS_PDL_URL
      value: "{{DOKARKIVAVLEVERING_ENDPOINTS_PDL_URL}}"
    - name: DOKARKIVAVLEVERING_ENDPOINTS_PDL_SCOPE
      value: "{{DOKARKIVAVLEVERING_ENDPOINTS_PDL_SCOPE}}"
    - name: DOKARKIVAVLEVERING_ACTIVEDIRECTORY_BASEDN
      value: "{{AD_NAVUSER_BASEDN}}"
    - name: SFTP_URL
      value: "{{ SFTP_URL }}"
    - name: SFTP_USERNAME
      value: "srvDokarkivavlevering"
    - name: SFTP_PRIVATEKEYFILE
      value: "/var/run/secrets/nais_secrets/privatekey.key"
    - name: DOKARKIVAVLEVERING_BATCHSIZE
      value: "200"
    - name: DOKARKIVAVLEVERING_FILOMRAADE_WORK
      value: "/tmp"
    - name: AVLEVERING_PERIODE_STARTDATO
      value: "{{periodestart}}"
    - name: AVLEVERING_PERIODE_SLUTTDATO
      value: "{{periodeslutt}}"
    - name: AVLEVERING_TEMA
      value: "{{tema}}"
    - name: AVSLUTTSAK_TEMA
      value: "{{tema}}"
    - name: AVSLUTTSAK_AVSLUTTETDATO
      value: "{{avsluttetDato}}"
    - name: AVSLUTTSAK_ADMINISTRATIVENHET
      value: "{{administrativEnhet}}"
    - name: AVSLUTTSAK_REFERANSE
      value: "{{referanse}}"
    - name: SPRING_PROFILES_ACTIVE
      value: "{{profile}}"
  webproxy: true
  azure:
    application:
      enabled: true