apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: dokarkivavlevering
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  ttlSecondsAfterFinished: 100
  image: {{image}}
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "4096Mi"
      cpu: "4000m"
  env:
    - name: SPRING_LDAP_URLS
      value: "{{SPRING_LDAP_URLS}}"
    - name: SPRING_DATASOURCE_URL
      value: "{{SPRING_DATASOURCE_URL}}"
    - name: VAULT_TOKEN_PATH
      value: /var/run/secrets/nais.io/vault/vault_token
    - name: AVLEVERING_PDLURL
      value: "{{PDL_URL}}"
    - name: AVLEVERING_EREGURL
      value: "{{EREG_URL}}"
    - name: AVLEVERING_STSTOKENURL
      value: "{{SECURITY_TOKEN_SERVICE_TOKEN_URL}}"
    - name: AVLEVERING_ACTIVEDIRECTORY_BASEDN
      value: "{{AD_NAVUSER_BASEDN}}"
    - name: AVLEVERING_PERIODE_STARTDATO
      value: "{{periodestart}}"
    - name: AVLEVERING_PERIODE_SLUTTDATO
      value: "{{periodeslutt}}"
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVDOKAVLEVERING }}
        mountPath: "/secrets/serviceuser/srvdokavlevering"
      - kvPath: {{ SRV_LINUX }}
        mountPath: "/var/run/secrets/nais.io/ldap"
      - kvPath: {{ DOKARKIV_DS }}
        mountPath: "/var/run/secrets/nais.io/dokarkivDS"
