name: Avslutt alle saker for et gitt tema [dev-fss]
on:
  workflow_dispatch:
    inputs:
      referanse:
        description: 'Jira-saksid (referanse til bestillingen)'
        required: true
      avsluttetDato:
        description: 'Tidspunkt når sakene ble avsluttet. Settes kun dersom alle sakene på tema skal merkes med samme avsluttet dato. Format: yyyy-MM-ddThh:mm'
        required: false
      administrativEnhet:
        description: 'Navn på enhet som er ansvarlig for sakene. Settes kun dersom alle sakene på tema skal merkes med samme administrative enhet.'
        required: false

jobs:
  build:
    name: Build image
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: navikt/dok-workflows/.github/workflows/build-app-gar.yml@main
    secrets: inherit
    with:
      java-version: '25'

  deploy:
    name: Deploy job to dev
    needs: build
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - name: Deploy job to NAIS dev-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          PRINT_PAYLOAD: true
          CLUSTER: dev-fss
          RESOURCE: nais/naiserator.yaml
          VAR: image=${{needs.build.outputs.image}},profile=avsluttSaker,referanse=${{github.event.inputs.referanse}},avsluttetDato=${{github.event.inputs.avsluttetDato}},administrativEnhet=${{github.event.inputs.administrativEnhet}}
          VARS: nais/dev-config.json
          WAIT: true
          TIMEOUT: 1h
