name: Test manual action run
on:
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      periodeStart:
        description: 'Start-dato (f.o.m) for avlevering'
        required: true
      periodeSlutt:
        description: 'Slutt-dato (t.o.m) for avlevering'
        required: true

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/dokarkivavlevering:${{ github.sha }}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      - name: Build and run tests
        run: mvn -B package --file pom.xml
#  build:
#    name: Build and push Docker container
#    needs: test
#    if: (github.event_name != 'pull_request')
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '11.x'
#      - name: Cache Maven packages
#        uses: actions/cache@v2
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-m2-
#      - name: Build JAR
#        run: ./mvn -B clean -DskipTests
#      - name: Build and publish Docker image
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          docker build . --pull --tag ${IMAGE}
#          echo "$GITHUB_TOKEN" | docker login --username "$GITHUB_REPOSITORY" --password-stdin https://docker.pkg.github.com
#          docker push ${IMAGE}
#  deploy-dev:
#    name: Deploy to NAIS dev-fss
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: nais/deploy/actions/deploy@v1
#        env:
#          PRINT_PAYLOAD: true
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: dev-fss
#          RESOURCE: .nais/naiserator.yaml
#          VARS: .nais/dev-config.json