name: Deploy dokarkivavlevering [prod-fss]
on:
  workflow_dispatch:
    inputs:
      periodeStart:
        description: 'Periode start (f.o.m) for avlevering. YYYY-MM-DD'
        required: true
      periodeSlutt:
        description: 'Periode slutt (t.o.m) for avlevering. YYYY-MM-DD'
        required: true
      tema:
        description: 'Tema for avlevering'
        required: true

jobs:
  build:
    name: Build image
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: navikt/dok-workflows/.github/workflows/build-app-gar.yml@main
    secrets: inherit
    with:
      java-version: '21'

  deploy:
    name: Deploy job to prod
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy job to NAIS prod-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          PRINT_PAYLOAD: true
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: nais/naiserator.yaml
          VAR: image=${{needs.build.outputs.image}},periodestart=${{github.event.inputs.periodeStart}},periodeslutt=${{github.event.inputs.periodeSlutt}},tema=${{github.event.inputs.tema}}
          VARS: nais/prod-config.json
          WAIT: true
          TIMEOUT: 3h